name: Build
run-name: build ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  build:
  strategy:
    fail-fast: false
    matrix:
      build:
        - name: "linux/amd64"
          os: "ubuntu-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true
          cache-dependency-path: go.sum