name: Build
run-name: build ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'linux/amd64'
            os: 'ubuntu-24.04'
          - name: 'linux/arm'
            os: 'ubuntu-24.04-arm'
    runs-on: ${{ matrix.build.os }}
    name: ${{ matrix.build.name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum
      - name: install 
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
          go get ./...
      - name: build
        run: go tool wails3 task linux:package
  windows:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'windows/amd64'
            os: 'windows-2025'
          - name: 'windows/arm'
            os: 'windows-11-arm'
    runs-on: ${{ matrix.build.os }}
    name: ${{ matrix.build.name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          cache-dependency-path: go.sum
      - name: download dependencies
        run: go get ./...
      - name: build
        run: go tool wails3 task windows:package