name: Build
run-name: build ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true
          cache-dependency-path: go.sum