name: Build
run-name: build ${{ github.ref_name }}
on:
  push:
    branches:
      - main
      - "releases/**"
jobs:
  build:
    name: linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
          check-latest: true
          cache-dependency-path: go.sum
      - name: install dependencies
        run: |
          sudo apt-get -yq update
          sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
      - name: install wails3
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
